language: python

python:
- '3.4'
- '3.5'
- '3.6'

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy jupyter
  - source activate test-environment
  - pip install -r requirements.txt

script: 
  - ./ci/test_notebooks.sh "AdvancedPif"
  - ./ci/test_notebooks.sh "AdvancedQueries"
  - ./ci/test_notebooks.sh "ImportVASP"
  - ./ci/test_notebooks.sh "IntroQueries"
  - ./ci/test_notebooks.sh "MLonCitrination"
  - ./ci/test_notebooks.sh "WorkingWithPIFs"
